### ISSUE TITLE
Support labels for App Configuration extension

### ISSUE THREAD

**Issue by fhavel** [quarkiverse/quarkus-azure-services#153]
Introduce configuration property for selecting list of labels.

**Comment by majguo** [comment]
Hello @fhavel The PR #158 is merged and I also kicked off a new release `1.0.2` with your contribution to support labels for App Configuration extension. Feel free to have a try once `1.0.2` is available in [Maven Central](https://central.sonatype.com/artifact/io.quarkiverse.azureservices/quarkus-azure-app-configuration).
