### ISSUE TITLE
Make possible to disable App Configuration by configuration property

### ISSUE THREAD

**Issue by fhavel** [quarkiverse/quarkus-azure-services#154]
Something like `quarkus.azure.app.configuration.enable=false` would be useful.

**Comment by majguo** [comment]
@fhavel FYI - We just released `1.0.4` which includes the support of disabling/enabling extension by configuration property including App Configuration. The doc [Quarkus Azure App Configuration Extension](https://docs.quarkiverse.io/quarkus-azure-services/dev/quarkus-azure-app-configuration.html#_extension_configuration_reference) is also updated accordingly by adding how to disable/enable the extension. If you’re looking for a complete code sample, you can find it from [azure-services-disabled](https://github.com/quarkiverse/quarkus-azure-services/tree/1.0.4/integration-tests/azure-services-disabled).

**Comment by fhavel** [comment]
I just tested it, works as expected. Thank you!
