### ISSUE TITLE
Support async client for azure-storage-blob extension

### ISSUE THREAD

**Issue by majguo** [quarkiverse/quarkus-azure-services#181]
The idea/requirement actually comes from #179: produce an async client so it can be used in reactive programming in Quarkus.

**Comment by hbzhou** [comment]
find a way to use async client, pls see the sample here
https://github.com/hbzhou/quarkus-storage-blob/blob/main/src/main/kotlin/com/itsz/StorageBlobAsyncResource.kt

**Comment by majguo** [comment]
@hbzhou Now we support async client in azure-storage-blob extension, see more information from https://github.com/quarkiverse/quarkus-azure-services/issues/175#issuecomment-2099605113.
