### ISSUE TITLE
azure-core prevents native image builds

### ISSUE THREAD

**Issue by fsantagostinobietti** [quarkiverse/quarkus-azure-services#204]
Integrating Azure libs (mainly azure-core dependency) into Quarkus application prevents my native build to complete successfully.

Workaround suggested in #161 does not solve the issue, probably due to the use of [quarkus-resteasy-reactive](https://quarkus.io/extensions/io.quarkus/quarkus-resteasy-reactive/) dependency in pom.xml 

Native build error logs look like this:
```
Error: Classes that should be initialized at run time got initialized during image building:

io.netty.buffer.UnpooledDirectByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledDirectByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledDirectByteBuf
...
io.netty.buffer.ByteBufAllocator the class was requested to be initialized at run time (from 'META-INF/native-image/io.netty/netty-buffer/native-image.properties' in 'file:///project/lib/io.netty.netty-buffer-4.1.94.Final.jar' with 'io.netty.buffer.ByteBufAllocator' and from feature io.quarkus.runner.Feature.beforeAnalysis with 'ByteBufAllocator.class'). To see why io.netty.buffer.ByteBufAllocator got initialized use --trace-class-initialization=io.netty.buffer.ByteBufAllocator
```

**Comment by majguo** [comment]
@fsantagostinobietti Could you pls provide a sample project which is able to reproduce the issue you described in the issue?

**Comment by majguo** [comment]
@fsantagostinobietti Building a Quarkus native image while integrating Azure libs (e.gl, `azure-core` dependency) does need some extra configuration, this is exactly the goal this repo tries to achieve. Basically, you have a few options:

* Utilize extensions of Azure libs this repo releases including [extensions](https://github.com/quarkiverse/quarkus-azure-services/tree/main/extensions) and [internal](https://github.com/quarkiverse/quarkus-azure-services/tree/main/internal), see samples from [integration-tests](https://github.com/quarkiverse/quarkus-azure-services/tree/main/integration-tests) and https://github.com/quarkiverse/quarkus-opentelemetry-exporter/pull/143 which utilized internal extension `quarkus-azure-http-client-vertx`.
* Reference raw native-image config from azure-sdk-for-java and re-write it using Quarkus way, e.g., https://github.com/Azure/azure-sdk-for-java/tree/main/sdk/core/azure-core-http-netty/src/main/resources/META-INF/native-image/com.azure/azure-core-http-netty.
* Open issue(s) in this repo for your specific requirements on what Azure libs you want to build in a Quarkus native image, we'll prioritize accordingly.

I'm going to close the issue as for now and feel free to re-open or open new issues if you have more information and comments.
