### ISSUE TITLE
Publish internal deployment libs

### ISSUE THREAD

**Issue by brunobat** [quarkiverse/quarkus-azure-services#214]
Because the internal libs don't seem to publish the deployment artifacts, it's not possible to include them in outside projects, like the Otel exporter. 
See: https://github.com/quarkiverse/quarkus-opentelemetry-exporter/pull/143

**Comment by brunobat** [comment]
Interesting, I was hit by resolution errors. Will try again soon.

**Comment by majguo** [comment]
@brunobat I do see internal libs (e.g., `quarkus-azure-http-client-vertx`) is successfully used in https://github.com/quarkiverse/quarkus-opentelemetry-exporter/pull/143, closing the issue now.

**Comment by majguo** [comment]
FYI @edburns @m-reza-rahman.
