### ISSUE TITLE
Dead guide link for keyvault extension

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-azure-services#234]
The metadata for the keyvault extension lists https://docs.quarkiverse.io/quarkus-azure-services/dev/quarkus-azure-key-vault.html as a guides link, but that link isn't live yet. 

I suggest either
- Doing the work to set up docs at that endpoint (https://hub.quarkiverse.io/#documenting-your-extension has instructions)
- Removing the guides link until the guides are ready (and, ideally, republishing)

**Comment by galiacheng** [comment]
Thanks for finding this @holly-cummins I am working on it.

**Comment by majguo** [comment]
@holly-cummins I verified that the broken guide link https://docs.quarkiverse.io/quarkus-azure-services/dev/quarkus-azure-key-vault.html works now.

**Comment by holly-cummins** [comment]
Good news, thanks!
