### ISSUE TITLE
What about renaming our package names?

### ISSUE THREAD

**Issue by agoncal** [quarkiverse/quarkus-azure-services#27]
I renamed the packages `io.quarkiverse.azureservices.azure.*` to `io.quarkiverse.azureservices.*` according to the Quarkiverse naming conventions. This way we avoid the duplication `azureservices.azure`.

@majguo we could also rename our packages `io.quarkiverse.azure.*` instead of having `io.quarkiverse.azureservices`. It would also fit better with the configuration keys that are called `quarkus.azure.` WDYT?

**Comment by melloware** [comment]
i prefer just `.azure` as its more concise. Just my two cents.

**Comment by agoncal** [comment]
Yes, I also prefer `.azure`. Just want to know @majguo POV

**Comment by majguo** [comment]
@agoncal @melloware  Yes, I also like `.azure` as it's more concise.

**Comment by agoncal** [comment]
Cool. I'll rename the packages then
