### ISSUE TITLE
Support for Azure Keyvault

### ISSUE THREAD

**Issue by JoaoBrandao** [quarkiverse/quarkus-azure-services#63]
Hi,
It will be very useful and secure to have a dependency that allows us to connect our Quarkus Applications properties with Azure KeyVault to retrieve secrets.

The concept is very simple, just add a few properties to enable the extension to list all properties and select those that make a match with a specific placeholder.

**Example:**

`password: ${APPLICATION_USER_PASSWORD:localpassword}
`

In Spring Cloud there is already an extension for that https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault but this only works for spring I guess.

**Comment by agoncal** [comment]
@radcortez I think you've worked on this, don't you?

**Comment by radcortez** [comment]
Not the KeyVault. I did the Azure App Configuration.

I also had plans to implement the Key Vault support. I'll do it in the next few weeks.

**Comment by agoncal** [comment]
@radcortez there is already a [Key Vault extension in Camel](https://github.com/apache/camel-quarkus/tree/main/extensions-jvm/azure-key-vault), I thought you were involved in it. I'll try to migrate this extension as a high priority

**Comment by ppalaga** [comment]
> there is already a [Key Vault extension in Camel](https://github.com/apache/camel-quarkus/tree/main/extensions-jvm/azure-key-vault)

That one is JVM-only - i.e. it has no proper tests.

**Comment by radcortez** [comment]
I looked, and it is the specific Camel component, so it is not integrated with Quarkus Config system. We should provide proper integration with it.

**Comment by majguo** [comment]
@all-contributors please add @JoaoBrandao for bug

**Comment by galiacheng** [comment]
Hello @JoaoBrandao loading Secrets as properties is available now, please see https://docs.quarkiverse.io/quarkus-azure-services/dev/quarkus-azure-key-vault.html#_read_secrets_as_properties.

**Comment by galiacheng** [comment]
Close the issue, please let me know if you have any question.
