### ISSUE TITLE
Use the quarkus-azure- prefix for extensions

### ISSUE THREAD

**Issue by agoncal** [quarkiverse/quarkus-azure-services#64]
As discussed in https://github.com/quarkiverse/quarkus-azure-services/issues/61, it would be better to use the `quarkus-azure-` prefix for extensions. The `azure-` prefix might awake the impression that they are some sort of official Azure artifacts, which they are not.

**Comment by maxandersen** [comment]
Also our recommended naming convention is to have "quarkus-" first. We use that in places to strip "quarkus-" so it takes less space and "azure" would then be easier to spot. 

P.s. camel-quarkus is the unfortunate exception that confirms that rule :)

**Comment by ppalaga** [comment]
> P.s. camel-quarkus is the unfortunate exception that confirms that rule :)

ASF tends to have its own rules  ¯\_(ツ)_/¯

**Comment by agoncal** [comment]
I realize that the artifact ids follow the right convention `quarkus-azure-app-configuration` and `quarkus-azure-storage-blob` so far. I think it's better that the directory structure is named after the Azure service (Azure App Configuration and Azure Storage Blob) and the artifact id gets the `quarkus` prefix.
