### ISSUE TITLE
What is the expected time of release of this extensions?

### ISSUE THREAD

**Issue by fhavel** [quarkiverse/quarkus-azure-services#73]
Hello everyone,

I would like to use especially Azure configuration in my project.
I haven't found this information anywhere.

Thank you

**Comment by agoncal** [comment]
There is no ETA. It depends on #74 and #37. Hopefully in the coming weeks we will have these extensions fully tested and released.

**Comment by majguo** [comment]
Hello @fhavel @andreabettich Now these two extensions (azure-storage-blob & azure-app-configuration) are released!
* https://central.sonatype.com/artifact/io.quarkiverse.azureservices/quarkus-azure-app-configuration/1.0.0
* https://central.sonatype.com/artifact/io.quarkiverse.azureservices/quarkus-azure-storage-blob/1.0.0

You can also take a look at the followings on how to use them in your app:
* Docs: https://quarkiverse.io/quarkiverse-docs/quarkus-azure-services/dev/index.html
* [Azure App Configuration sample](https://github.com/quarkiverse/quarkus-azure-services/blob/main/integration-tests/azure-app-configuration): REST endpoint using the Quarkus extension to get the configuration stored in Azure App Configuration.
* [Azure Blob Storage sample](https://github.com/quarkiverse/quarkus-azure-services/blob/main/integration-tests/azure-storage-blob): REST endpoint using the Quarkus extension to upload and download files to/from Azure Blob Storage.
