### ISSUE TITLE
Support Azure Insights OpenTelemetry Exporter

### ISSUE THREAD

**Issue by melloware** [quarkiverse/quarkus-azure-services#81]
I originally posted here: https://github.com/quarkiverse/quarkus-opentelemetry-exporter/issues/33

Not sure if that is the right place or its should be here since this project is run by MS.

Library: https://learn.microsoft.com/en-us/java/api/overview/azure/monitor-opentelemetry-exporter-readme?view=azure-java-preview

Quarkus OLTP: https://quarkus.io/guides/opentelemetry#exporters

cc @jeanbisutti @heyams @trask

**Comment by majguo** [comment]
@all-contributors please add @melloware for bug

**Comment by brunobat** [comment]
I think the exporter should be implemented in the scope of https://github.com/quarkiverse/quarkus-opentelemetry-exporter/issues/33

**Comment by melloware** [comment]
This has been implemented in OpenTelemetry extension as @brunobat mentioned!
